/*
	Master UI Resource File
*/

#include "common.hpp" //Main init DO NOT TOUCH!
#include "admin_menu.hpp"
#include "auctions.hpp"
#include "bank.hpp"
#include "chop_shop.hpp"
#include "clothing.hpp"
#include "copHQ.hpp"
#include "deathScreen.hpp"
#include "emoji.hpp"
#include "faq.hpp"
#include "farmingSim.hpp"
#include "formular.hpp"
#include "fuelstation.hpp"
#include "gang.hpp"
#include "goldSafe.h"
#include "house_box.hpp"
#include "impound.hpp"
#include "InputMessage.hpp"
#include "jail_time.hpp"
#include "jobcenter.hpp"
#include "joinerUIdefines.hpp"
#include "joinerUIdialog.hpp"
#include "key_chain.hpp"
#include "LicensesDialog.hpp"
#include "lockpick.hpp"
#include "notify_cCords.hpp"
#include "perso.hpp"
#include "pInteraction.h"
#include "player_inv.hpp"
#include "prof_2.hpp"
#include "radarfalle.hpp"
#include "repaint.hpp"
#include "settings.h"
#include "shop_items.hpp"
#include "shops.hpp"
#include "smartphone.hpp"
#include "spawnSelection.hpp"
#include "speedtrap.hpp"
#include "staffManager.hpp"
#include "taxi_zentrale.hpp"
#include "taxianfrage.hpp"
#include "taxirufen.hpp"
#include "thrHQ.hpp"
#include "ticket.hpp"
#include "trunk.hpp"
#include "vehicleShop.h"
#include "virt_houseMenu.hpp"
#include "checkPlate.hpp"
#include "numberPlate.hpp"
